version: '3.9'

services:
  blog_db:
    container_name: blog_db
    image: postgres:13.1
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  blog_web:
    container_name: blog_web
    build:
      context: .
      target: django
    restart: unless-stopped
    depends_on:
      blog_db:
        condition: service_healthy
      blog_redis:
        condition: service_started
    ports:
      - "127.0.0.1:8585:8585"
    command: python blog/manage.py runserver 0.0.0.0:8585
    volumes:
      - .:/app
    env_file: .env

  blog_redis:
    container_name: blog_redis
    image: redis:5.0.12
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: unless-stopped

volumes:
  postgres_db:
    name: blog_db

networks:
  default:
    name: blog
