# Generated by Django 4.2.15 on 2024-08-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
